### PR TITLE
Use ES6 transpilation target

### PR DESCRIPTION
**Pull request by mszabo-wikia**
Most browsers that we care about[1] support ES6 for a while now, so let's transpile ad-engine to ES6 instead of ES5. This brings notable savings, for instance:

* `ucp-mobile` goes from 652 KiB to 454 KiB,
* `ucp-no-ads` goes from 315 KiB to 215 KiB.

For this to work, resolve circular dependencies in ad-slot.ts by using
type imports where possible and inlining the ADX constant which
currently cannot be imported without a circular dependency. Also update
pipeline code, as ES6 arrow functions do not have a prototype, so tests
started failing after converting them to ES6.

---
[1] https://caniuse.com/es6

### CODE REVIEW

**Review by dmnsobczak — APPROVED** [review]

**Comment by jbienkowski-fandom** [comment]
```
dist/platforms/bingebot/main.bundle.js 336K -> 236K
dist/platforms/comicvine/main.bundle.js 529K -> 376K
dist/platforms/f2/main.bundle.js 574K -> 396K
dist/platforms/gamefaqs/main.bundle.js 536K -> 383K
dist/platforms/gamespot/main.bundle.js 556K -> 402K
dist/platforms/giantbomb/main.bundle.js 530K -> 377K
dist/platforms/metacritic-neutron/main.bundle.js 537K -> 383K
dist/platforms/metacritic/main.bundle.js 507K -> 389K
dist/platforms/sports/main.bundle.js 507K -> 353K
dist/platforms/tvguide/main.bundle.js 559K -> 405K
dist/platforms/ucp-desktop/main.bundle.js 621K -> 431K
dist/platforms/ucp-mobile/main.bundle.js 633K -> 437K
dist/platforms/ucp-no-ads/main.bundle.js 313K -> 206K
```

**Review by szymon-nawrocki — APPROVED** [review]

**Comment by jbienkowski-fandom** [comment]
After removing `core-decorators` as dependency and using `tslib` [1] by setting `importHelpers` in `tsconfig.json` the final results are:

```
dist/platforms/bingebot/main.bundle.js - 341.83K -> 211.68K (-38.00%)
dist/platforms/comicvine/main.bundle.js - 540.18K -> 333.48K (-38.00%)
dist/platforms/f2/main.bundle.js - 585.69K -> 338.05K (-42.00%)
dist/platforms/gamefaqs/main.bundle.js - 547.30K -> 340.16K (-37.00%)
dist/platforms/gamespot/main.bundle.js - 566.86K -> 358.61K (-36.00%)
dist/platforms/giantbomb/main.bundle.js - 541.15K -> 334.46K (-38.00%)
dist/platforms/metacritic-neutron/main.bundle.js - 548.11K -> 340.08K (-37.00%)
dist/platforms/metacritic/main.bundle.js - 553.45K -> 346.33K (-37.00%)
dist/platforms/sports/main.bundle.js - 518.30K -> 306.15K (-40.00%)
dist/platforms/tvguide/main.bundle.js - 570.19K -> 360.82K (-36.00%)
dist/platforms/ucp-desktop/main.bundle.js - 632.96K -> 371.11K (-41.00%)
dist/platforms/ucp-mobile/main.bundle.js - 644.04K -> 374.67K (-41.00%)
dist/platforms/ucp-no-ads/main.bundle.js - 324.52K -> 191.13K (-41.00%)
```

<hr>

[1] - https://www.tomsquest.com/blog/2020/02/think-carbon-reduce-typescript-bundle-size/

**Comment by mszabo-wikia** [comment]
@jbienkowski-fandom these are great numbers! 📉

**Comment by dmnsobczak** [comment]
@jbienkowski-fandom 
`importHelpers` - why shit like that is not enabled by default (╯°□°）╯︵ ┻━┻
Nicely done ❤️

**Review by kwfandom — APPROVED** [review]

**Pull request merged**
