### PR TITLE
ADEN-12839-2 Hotfixing bids refreshing on TVGuide

### PR DESCRIPTION
**Pull request by dmnsobczak**

### CODE REVIEW

**Comment by adi-wesolowski-fandom** [comment]
lgtm

**Review by adi-wesolowski-fandom — COMMENTED** [review]
lgtm

**Review by adi-wesolowski-fandom — APPROVED** [review]

**Review by szymon-nawrocki — APPROVED** [review]

**Review by jbienkowski-fandom — APPROVED** [review]
Out of score for this hotfix, but a follow up ticket could be creating some kind of interface (type) for `basicContext` to avoid such errors in the future.

**Comment by dmnsobczak** [comment]
@jbienkowski-fandom This pandora box is already opened xD
https://fandom.atlassian.net/browse/ADEN-11165

**Pull request merged**
